import 'dart:convert';
import 'dart:io';

/// Compile reviewed ARB files. No network calls or translation service.
void main() {
  final catalogues = <String, Map<String, dynamic>>{
    for (final locale in ['en', 'pt_BR', 'es'])
      locale:
          jsonDecode(File('lib/l10n/strings_$locale.arb').readAsStringSync())
              as Map<String, dynamic>,
  };
  final english = catalogues['en']!;
  final keys = english.keys.where((key) => !key.startsWith('@')).toSet();
  final output = StringBuffer(
    '// GENERATED by tool/generate_localizations.dart. Edit the ARB sources.\n',
  );
  String literal(String value) => jsonEncode(value).replaceAll(r'$', r'\$');
  for (final entry in catalogues.entries) {
    final translatedKeys = entry.value.keys
        .where((key) => !key.startsWith('@'))
        .toSet();
    if (!keys.containsAll(translatedKeys) ||
        !translatedKeys.containsAll(keys)) {
      throw FormatException('Message key mismatch: ${entry.key}');
    }
    final name = switch (entry.key) {
      'pt_BR' => 'Pt',
      'es' => 'Es',
      _ => 'En',
    };
    output.writeln('const messages$name = <String, String>{');
    for (final key in keys) {
      final source = english[key] as String;
      final value = entry.value[key] as String;
      Set<String> placeholders(String text) =>
          RegExp(r'\{p\d+\}').allMatches(text).map((m) => m[0]!).toSet();
      final expected = placeholders(source);
      final actual = placeholders(value);
      if (!expected.containsAll(actual) || !actual.containsAll(expected)) {
        throw FormatException('Placeholder mismatch: ${entry.key}: $key');
      }
      output.writeln('  ${literal(source)}: ${literal(value)},');
    }
    output.writeln('};');
  }
  File('lib/l10n/messages.g.dart').writeAsStringSync(output.toString());
  stdout.writeln(
    '${keys.length} messages validated and compiled in three languages.',
  );
}
